"""OpenDART 어댑터 — 공시·재무제표 조회(driven adapter).

기존 `services.dart` / `dart_report_parser` / `dart_throttle` 공개 API 를 이 패키지에서
그대로 재노출해, 호출측은 `from app.adapters import dart` 후 `dart.fetch_*` 를 쓴다.
"""

from app.adapters.dart import report_parser, throttle
from app.adapters.dart.client import (
    BwIssue,
    CbIssue,
    CorpMapping,
    DartQuotaExceeded,
    Disclosure,
    Dividend,
    HyslrRow,
    IncomeEquity,
    LargestShareholders,
    MajorHolder,
    RelatedParty,
    StockTotal,
    configure_from_settings,
    extract_ownership_reason,
    fetch_bw_issuance,
    fetch_cb_issuance,
    fetch_corp_mappings,
    fetch_disclosures,
    fetch_dividend,
    fetch_document_text,
    fetch_full_statements,
    fetch_full_statements_by_div,
    fetch_full_statements_ofs,
    fetch_hyslr_rows,
    fetch_income_and_equity,
    fetch_income_summary,
    fetch_largest_shareholders,
    fetch_major_shareholders,
    fetch_ownership_changes,
    fetch_related_companies,
    fetch_roe,
    fetch_stock_total,
    find_all_periodic_reports,
    find_ipo_reports,
    find_periodic_report,
    parse_full_statements,
)
from app.adapters.dart.report_parser import (
    fetch_report_zip,
    parse_cf_depreciation,
    parse_sce_tables_from_zip,
)

__all__ = [
    "BwIssue",
    "CbIssue",
    "CorpMapping",
    "DartQuotaExceeded",
    "Disclosure",
    "Dividend",
    "HyslrRow",
    "IncomeEquity",
    "LargestShareholders",
    "MajorHolder",
    "RelatedParty",
    "StockTotal",
    "configure_from_settings",
    "extract_ownership_reason",
    "fetch_bw_issuance",
    "fetch_cb_issuance",
    "fetch_corp_mappings",
    "fetch_disclosures",
    "fetch_dividend",
    "fetch_document_text",
    "fetch_full_statements",
    "fetch_full_statements_by_div",
    "fetch_full_statements_ofs",
    "fetch_hyslr_rows",
    "fetch_income_and_equity",
    "fetch_income_summary",
    "fetch_largest_shareholders",
    "fetch_major_shareholders",
    "fetch_ownership_changes",
    "fetch_related_companies",
    "fetch_report_zip",
    "fetch_roe",
    "fetch_stock_total",
    "find_all_periodic_reports",
    "find_ipo_reports",
    "find_periodic_report",
    "parse_cf_depreciation",
    "parse_full_statements",
    "parse_sce_tables_from_zip",
    "report_parser",
    "throttle",
]
